version: '3.9'
services:


  frontend:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./:/app
    ports:
      - 3000:3000
    networks:
      - demo-network

networks:
  demo-network:
    name: demo
